__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
# include: "rules/longqc.smk" not finished rule
include: "rules/fastqc.smk"
include: "rules/gatk.smk"
include: "rules/happy.smk"
include: "rules/mosdepth.smk"
include: "rules/multiqc.smk"
include: "rules/peddy.smk"
include: "rules/picard.smk"
include: "rules/rseqc.smk"
include: "rules/samtools.smk"
include: "rules/verifybamid2.smk"


rule all:
    input:
        unpack(compile_output_list),
