# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/fastqc.smk"
include: "rules/picard_duplication_metrics.smk"
include: "rules/picard_alignment_summary_metrics.smk"
include: "rules/picard_hs_metrics.smk"
include: "rules/picard_insert_size.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
