$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: path to resources.yaml file
  samples:
    type: string
    description: path to samples.tsv file
  units:
    type: string
    description: path to units.tsv file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    description: paths to reference files
    properties:
      design_bed:
        type: string
        description: path to bed file for design regions
      design_intervals:
        type: string
        description: path to picard-style bed file for design regions
      fasta:
        type: string
        description: path to reference fasta file
      wgs_intervals:
        type: string
        description: path to picard-style interval file for wgs regions
    required:
      - fasta
  
  bcftools_stats:
    type: object
    description: parameters for bcftools_stats
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  cramino:
    type: object
    description: parameters for cramino
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  fastqc:
    type: object
    description: parameters for fastqc
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  gatk_calculate_contamination:
    type: object
    description: parameters for gatk_calculate_contamination
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_get_pileup_summaries:
    type: object
    description: parameters for gatk_get_pileup_summaries
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      sites:
        type: string
        description: sites to pileup (eg small_exac_common.vcf from GnomAD)
      variants:
        type: string
        description: varaints to pileup (eg small_exac_common.vcf from GnomAD, usually same as sites)
      extra:
        type: string
        description: parameters that should be forwarded

  mosdepth:
    type: object
    description: parameters for mosdepth
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      by:
        type: string
        description: by flag
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  mosdepth_bed:
    type: object
    description: parameters for mosdepth_bed
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  multiqc:
    type: object
    description: parameters for multiqc
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      reports:
        type: object
        description: list of multiqc reports that will be generated
        additionalProperties:
          type: object
          properties:
            config:
              type: string
              description: path to config file
            included_unit_types:
              type: array
              description: unit types that will be included
              items:
                type: string
                pattern: "^(N|T|R)$"
            qc_files:
              type: array
              description: list with path to qc-files that will be used to generate a MultiQC report
              items:
                type: string
            required:
              - qc_files
    required:
      - reports
  
  # Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  multiqc_longread:
    type: object
    description: parameters for multiqc_longread
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      reports:
        type: object
        description: list of multiqc reports that will be generated
        additionalProperties:
          type: object
          properties:
            config:
              type: string
              description: path to config file
            included_unit_types:
              type: array
              description: unit types that will be included
              items:
                type: string
                pattern: "^(N|T|R)$"
            qc_files:
              type: array
              description: list with path to qc-files that will be used to generate a MultiQC report
              items:
                type: string
            required:
              - qc_files
    required:
      - reports
  
  nanoplot:
    type: object
    description: parameters for nanoplot
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  peddy:
    type: object
    description: parameters for peddy
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  picard_collect_alignment_summary_metrics:
    type: object
    description: parameters for picard_collect_alignment_summary_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  picard_collect_duplication_metrics:
    type: object
    description: parameters for picard_collect_duplication_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for picard_collect_alignment_summary_metrics
      container:
        type: string
        description: name or path to docker/singularity container

  picard_collect_gc_bias_metrics:
    type: object
    description: parameters for picard_collect_gc_bias_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  picard_collect_hs_metrics:
    type: object
    description: parameters for picard_collect_hs_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: |
          parameters that should be forwarded
          NOTE: Increase COVERAGE_CAP=5000 if you have high coverage data or RNA data

  picard_collect_insert_size_metrics:
    type: object
    description: parameters for picard_collect_insert_size_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  picard_collect_multiple_metrics:
    type: object
    description: parameters for picard_collect_multiple_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      output_ext:
        type: array
        description: list of output file extensions
        items:
          type: string

  picard_collect_wgs_metrics:
    type: object
    description: parameters for picard_collect_wgs_metrics
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  samtools_stats:
    type: object
    description: parameters for samtools_stats
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded


  sequali:
    type: object
    description: parameters for sequali
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  verifybamid2:
    type: object
    description: parameters for verifybamid2
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded


required:
  - samples
  - units
  - resources
  - default_container
