resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.9"

reference:
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"
  design_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"
  fasta: "reference/HES45.fna"
  wgs_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

gatk_calculate_contamination:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_get_pileup_summaries:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  sites: "reference/chr1_small_exac_common_3.hg19.vcf"
  variants: "reference/chr1_small_exac_common_3.hg19.vcf"

mosdepth:
  by: "500"
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: "--fast-mode --no-per-base"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    DNA:
      included_unit_types: ['N', 'T']
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.{ext}"
        - "qc/picard_collect_wgs_metrics/{sample}_{type}.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed/{sample}_{type}.per-base.bed.gz"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
    RNA:
      included_unit_types: ['R']
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/rseqc_gene_body_coverage/{sample}_{type}.geneBodyCoverage.txt"
        - "qc/rseqc_inner_distance/{sample}_{type}.inner_distance.txt"

peddy:
  container: "docker://hydragenetics/peddy:0.4.8"
  extra: ""

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_gc_bias_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.0"
  output_ext:
    - "gc_bias.pdf"

picard_collect_wgs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

rseqc_gene_body_coverage:
  bed: "reference/gene_model.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

rseqc_inner_distance:
  bed: "reference/gene_model.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"
