# requires somalier specific reference paths
# Uses filtered hg19 sites that match HES45.fna chromosome lengths

samples: "samples_somalier.tsv"
units: "units_somalier.tsv"

somalier_extract:
  sites: "reference/sites.hg19.HES45.vcf.gz"
  container: "docker://brentp/somalier:v0.2.16"

somalier_relate:
  container: "docker://brentp/somalier:v0.2.16"

somalier_mqc:
  mqc_config: "../../config/somalier_mqc_config.yaml"

multiqc:
  reports:
    multiqc:
      qc_files:
        - "qc/somalier/somalier_samples_mqc.tsv"
      included_unit_types: ["N", "T"]
      config: "../../config/somalier_mqc_config.yaml"
  use_input_files_only: true
  threads: 1
  container: "docker://ewels/multiqc:v1.13"
