# requires system-specific reference paths
# Override reference to use standard hg19 (required for somalier)
reference:
  fasta: "/beegfs-storage/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"

samples: "samples_somalier.tsv"
units: "units_somalier.tsv"

somalier_extract:
  sites: "reference/sites.vcf.gz"
  container: "docker://brentp/somalier:v0.2.16"

somalier_relate:
  container: "docker://brentp/somalier:v0.2.16"

somalier_mqc:
  config: "reference/somalier_mqc_config.yaml"

multiqc:
  reports:
    multiqc:
      qc_files:
        - "qc/somalier/somalier_samples_mqc.tsv"
      included_unit_types: ["N", "T"]
      config: "reference/somalier_mqc_config.yaml"
  use_input_files_only: true
  threads: 1
  container: "docker://ewels/multiqc:v1.13"
